openapi: 3.0.0
info:
  version: '1.0'
  title: "TheCameron"
  description: TheCameron is an API that allows users to view and write articles, post reactions to them and follow and stay updated on the various authors
  license:
    name: MIT
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost
    
paths:
    /xxx:
    
components:
  schemas: