openapi: 3.0.0
info:
  version: '1.0'
  title: "TheCameron"
  description: TheCameron is an API that allows users to view and write articles, post reactions to them and follow and stay updated on the various authors
  license:
    name: MIT
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost
    
paths:
    /user:
      post:
        description: >-
          Create a new user.
        summary: New user.
        requestBody:
          content:
            application/json:
              schema:
                type: object
                required: 
                  - name
                  - surname
                  - email
                  - password
                  - username
                properties:
                  name:
                    type: string
                    description: "Name"
                  surname:
                    type: string
                    description: "Surname"
                  email:
                    type: string
                    description: "email"
                  password:
                    type: string
                    description: "Password"
                  username:
                    type: string
                    description: "Username"
        responses:
          '201':
            description: "Created new user."
            headers:
              'Location':
                schema:
                  type: string
                  description: Link to the new user.
          '400':
            description: "Errore."
          '403':
            description: "Username already exist."
    
components:
  schemas: